### ISSUE TITLE
Dude i  gotta problem to run this container,,,This deadline container is needed for my thesis and is a requirement for me to graduate,,,please help thx you

### ISSUE THREAD

**Issue by bbnk03** [postwork-io/deadline_docker#4]
Secrets Management: An error occurred while trying to assign a Server role and grant key access to this machine. Check the bitrock_installer log file in /tmp for more information.
Problem running post-install step. Installation may not complete correctly
 Secrets Management: Failed to assign a Server role and grant key access to this machine. You will need to run 'deadlinecommand Secrets ConfigureServerMachine' after the installation. Check the bitrock_installer log file in /tmp for more information.

Error: Could not connect to any of the specified Mongo DB servers defined in the "Hostname" parameter of the "settings/connection.ini" file in the root of the Repository.
The following errors were encountered:
* deadline-db: Unable to authenticate username 'OU=PIPELINE,O=POSTWORK.IO,CN=deadline-client' using protocol 'MONGODB-X509'. (FranticX.Database.DatabaseConnectionException)
WARNING: Ignoring HOME environment because effective user is root.ng
ERROR: DataController threw an unexpected exception during initialization: FranticX.Database.DatabaseConnectionException: Could not connect to any of the specified Mongo DB servers defined in the "Hostname" parameter of the "settings/connection.ini" file in the root of the Repository.

The following errors were encountered:
* deadline-db: Unable to authenticate username 'OU=PIPELINE,O=POSTWORK.IO,CN=deadline-client' using protocol 'MONGODB-X509'.
   at Deadline.StorageDB.MongoDB.MongoDBUtils.HandleException(String serverAddress, Exception ex, String optionalMessagePrefix)
   at Deadline.StorageDB.RepositoryConnect.DirectRepositoryStorage.a(DirectConnectionSettings os, Int32 ot, X509Certificate2 ou, X509Certificate2 ov)
   at Deadline.StorageDB.RepositoryConnect.DirectRepositoryStorage..ctor(RepositoryConnectionSettings repositoryConnectionSettings, Int32 connectionPoolSize, Boolean leanConnect, X509Certificate2 dbClientCert, X509Certificate2 rootCA, Boolean skipVersionCheck, Boolean isRCS, DataControllerUpdateClient updateClient, HttpClient httpClient)
   at Deadline.StorageDB.RepositoryConnect.DirectRepositoryStorage..ctor(RepositoryConnectionSettings repositoryConnectionSettings, X509Certificate2 dbClientCert, X509Certificate2 rootCA, Boolean skipVersionCheck, Boolean isRCS, DataControllerUpdateClient updateClient, HttpClient httpClient)
   at Deadline.StorageDB.RepositoryConnect.RepositoryStorageManager.ConnectToRepository(RepositoryConnectionSettings connSettings, Boolean skipVersionCheck, DataControllerUpdateClient updateClient, HttpClient httpClient)
   at Deadline.Controllers.DataController.ConnectToRepository(RepositoryConnectionSettings connectionSettings)
   at Deadline.Controllers.DataController.SetupConnectionSettings(RepositoryConnectionSettings connSettings)
   at Deadline.Controllers.DataController.Initialize(RepositoryConnectionSettings connSettings)
Could not connect to Deadline Repository: Could not connect to any of the specified Mongo DB servers defined in the "Hostname" parameter of the "settings/connection.ini" file in the root of the Repository.

**Comment by nubi** [comment]
I have the same issue. I think it has to do with deadline 10.3 and higher.
